# Generated by Django 4.2.3 on 2023-12-03 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Col1', models.CharField(max_length=50)),
                ('Col2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col3', models.CharField(max_length=50)),
                ('Col4', models.CharField(max_length=50)),
                ('Col5', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col6', models.CharField(max_length=50)),
                ('Col7', models.CharField(max_length=50)),
                ('Col8', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col9', models.CharField(max_length=50)),
                ('Col10', models.CharField(max_length=50)),
                ('Col11', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col12', models.CharField(max_length=50)),
                ('Col13', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col14', models.CharField(max_length=50)),
                ('Col15', models.CharField(max_length=50)),
                ('Col16', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col17', models.CharField(max_length=50)),
                ('Col18', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Col19', models.CharField(max_length=50)),
                ('Col20', models.CharField(max_length=50)),
                ('Col21', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
