# Generated by Django 4.2.3 on 2023-12-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predict',
            name='Col11',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col13',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col16',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col18',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col21',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col5',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='predict',
            name='Col8',
            field=models.IntegerField(),
        ),
    ]
