# Generated by Django 4.2.3 on 2023-12-03 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0002_alter_predict_col11_alter_predict_col13_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predict',
            name='Col21',
        ),
    ]
