# Generated by Django 4.2.3 on 2023-12-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinelearning', '0003_remove_predict_col21'),
    ]

    operations = [
        migrations.AddField(
            model_name='predict',
            name='Col21',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
